### ISSUE TITLE
Error "assert db is not None"

### ISSUE THREAD

**Issue by jcguu95** [karlicoss/fbmessengerexport#10]
Setup the cookies as in `readme`, and ran 
```
$ python3 -m fbmessengerexport.export --cookies '{"c_user": "100000000000000", "datr": "dddddddddddddddddddddddd", "fr": "dlaskjdlakjsldkjL.Alksajdlkjaslkdjalskjdlkajs.lakds1.S-.AAA.0.0.lsakdd.asdasdadasd", "noscript": "1", "sb": "alsjdlasdklajsdlkajsdlad", "xs": "lkajsdalskjdalskjdw%dsd%lksjdlaksjld%lskjdl%lksajds"}'
```
(I've changed the secret manually.)

and received an error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/me/.local/lib/python3.9/site-packages/fbmessengerexport/export.py", line 363, in <module>
    main()
  File "/home/me/.local/lib/python3.9/site-packages/fbmessengerexport/export.py", line 285, in main
    db = args.db; assert db is not None
```

**Comment by karlicoss** [comment]
Hey, you need to pass --db argument, otherwise the script doesn't know where to dump messages. 
(by the way not sure if it works at the moment anyway, the upstream library I'm using for Facebook api has been broken for the past month :( )

**Comment by karlicoss** [comment]
I guess you fixed it :) https://github.com/karlicoss/fbmessengerexport/pull/11
