### ISSUE TITLE
Errors using --login during first-time setup

### ISSUE THREAD

**Issue by troennes** [karlicoss/fbmessengerexport#8]
I had problems running first time setup with `./export --login`, getting this error: 

```
Traceback (most recent call last):
  File "./export.py", line 21, in <module>
    from .exporthelpers import logging_helper
ImportError: attempted relative import with no known parent package
```

I tried running it as a module instead, with `python3 -m fbmessengerexport.export --login`, which gave another error:

```
Traceback (most recent call last):
  File "./export.py", line 364, in <module>
    main()
  File "./export.py", line 278, in main
    args = parser.parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2043, in _parse_known_args
    self._get_value(action, action.default))
  File "/usr/lib/python3.8/argparse.py", line 2434, in _get_value
    result = type_func(arg_string)
  File "/home/kim/fbmessengerexport/src/fbmessengerexport/exporthelpers/export_helper.py", line 130, in check_params
    raise use_secrets
RuntimeError: Please use either --secrets file or individual --param arguments (see --help)
```

Seems there's a logic flaw raising a use_secrets message from a helper submodule when --login is provided. I commented out the lines in the check_params function and retried. That solved my problem.

**Comment by karlicoss** [comment]
The first one is a typo in readme, yeah it won't work with just `./export.py` call anymore.. I guess need to remove the executable bit, so it's not confusing people.
For the second, yeah, indeed.. I guess in the meantime the easiest is to just use an arbitrary cookie string (e.g. `--login --cookie whatever`).
I'll update the readme, thanks!

**Comment by troennes** [comment]
Great! Thanks for the quick fix!
